### ISSUE TITLE
Compiling the AddFunction example (chapter 1) with distutils

### ISSUE THREAD

**Issue by EPiress** [redbrain/cython-book#6]
Hey,

So I have just started using Cython, but I am having trouble running the "ownmodule" example with distutils.

If I run make, I can get the right result, but I really want to use distutils, for simplicity.

This is what my setup.py looks like:

from distutils.core import setup, Extension
from Cython.Distutils import build_ext

modules = [
    Extension("PyAddFunction", sources=["PyAddFunction.pyx"])
]

setup(
    cmdclass={'build_ext': build_ext},
    ext_modules = modules
)

and it compiles with no error.

But when I try to import the module, I get the following error:

    from PyAddFunction import Add
ImportError: dlopen(/Users/PycharmProjects/project/PyAddFunction.so, 2): Symbol not found: _AddFunction
  Referenced from: /Users/PycharmProjects/project/PyAddFunction.so
  Expected in: flat namespace
 in /Users/PycharmProjects/project/PyAddFunction.so

How can I solve this error?
Thanks in advance,
EPiress

**Comment by philberty** [comment]
Did you get sorted ok I am on vacation but back on Monday :)

**Comment by EPiress** [comment]
Yes, I eventually understood what was missing in my code! Thanks
